export const CHARACTERS = [
    {
        id: 1,
        name: "Din Djarin",
        imagescn: "/assets/images/character/mandalorian.png",
        imagescn2: "/assets/images/character/mandalorian2.png",
        imagescn3: "/assets/images/character/mandalorian3.png",
        sum: "Known as the Mandalorian or Mando for short, was a human male Mandalorian foundling who worked as a bounty hunter during the New Republic Era. With his Mandalorian armor and distinctive beskar mask, Djarin was both well-equipped and enigmatic—a stranger whose past was shrouded in mystery. He was a battle-hardened warrior, a man of few words, and a formidable mercenary in an increasingly dangerous galaxy. After the fall of the Galactic Empire, Djarin made a name for himself as a member of the Bounty Hunters' Guild, collecting bounties as he traveled across the galaxy's Outer Rim Territories—far from the authority. ",
        home:"Unknown",
        Species: "Human",
        gender: "Male",
        eye: "Brown",
        skin: "Light",
        color: "chtitle chtitlecolor1",
    },
    {
        id: 2,
        name: "The Child",
        imagescn: "/assets/images/character/babyYoda.png",
        imagescn2: "/assets/images/character/babyYoda2.png",
        imagescn3: "/assets/images/character/babyYoda3.png",
        sum: "The Child was born around 41 BBY, and was held at a compound run by Nikto mercenaries on Arvala-7. While still an infant at the age of fifty years old, he was sought by an Imperial who hired a Mandalorian bounty hunter named Din Djarin to retrieve him However, Djarin chose not to leave the Child with the Imperials and saved him from the Imperial remnant facility. After attempting to hide with the Child along the fringes of the galaxy, Djarin returned to Nevarro to deal with the Imperials chasing the Child in hopes of keeping him safe. In the process, the Child became a Mandalorian foundling and a member of Djarins newly-created clan.",
        home:"Dagobah",
        Species: "Yoda's",
        gender: "Male",
        eye: "Brown",
        skin: "Green",
        color: "chtitle chtitlecolor1",
    },
    {
        id: 3,
        name: "Carasynthia Dune",
        image: "/assets/images/eps/s01e03vul.jpg",
        imagescn: "/assets/images/character/CaraDune.png",
        imagescn2: "/assets/images/character/CaraDune2.png",
        imagescn3: "/assets/images/character/CaraDune3.png",
        sum: "A human female Alderaanian who served as a shock trooper in the Alliance to Restore the Republic. Dune saw most of her action after the Battle of Endor hunting down former Imperial officials who had become warlords. After the Imperial warlords were seemingly gone and the Alliance became more politically organized, the Alliance focused more on peacekeeping tasks such as escorting delegates and suppressing riots. Dune came to regard these as tasks she had not signed up for. As a result, she left the Alliance and reinvented herself as a mercenary, putting her days of military discipline behind her. ",
        home:"Alderaan",
        Species: "Human",
        gender: "Female",
        eye: "Brown",
        skin:"Light",
        color: "chtitle chtitlecolor1",
    },
    {
        id: 4,
        name: "Kuiil",
        image: "/assets/images/eps/s01e03vul.jpg",
        imagescn: "/assets/images/character/Kuiil.png",
        imagescn2: "/assets/images/character/Kuiil2.png",
        imagescn3: "/assets/images/character/Kuiil3.png",
        sum: "Kuiil worked for the Galactic Empire as an indentured servant and Kuiil was an Ugnaught male who worked a lifetime to be free of servitude. He came to the out-of-the-way planet of Arvala-7 seeking peace, and worked as a vapor farmer who offered valuable skills to those who could meet his price. Eventually, criminals and mercenaries trespassed on his world[3] during the time of the New Republic, and at some point Kuiil encountered the Mandalorian bounty hunter Din Djarin.[5] After the plan to relieve The Child from being hunted went poorly, Kuiil was eventually tracked down, shot, and killed by Imperial scout troopers on speeder bikes. ",
        home:" Arvala-7",
        Species: "Ugnaught",
        gender: "Male",
        eye: "Green",
        skin:"Tan",
        color: "chtitle chtitlecolor1",
    },
    {
        id: 5,
        name: "Greef Karga",
        image: "/assets/images/eps/s01e03vul.jpg",
        imagescn: "/assets/images/character/greefKarga.png",
        imagescn2: "/assets/images/character/greefKarga2.png",
        imagescn3: "/assets/images/character/greefKarga3.png",
        sum: "A former disgraced magistrate before becoming an agent of the Bounty Hunters. In around 9 ABY, he met with the bounty hunter named Din Djarin in a cantina to accept four bounties the hunter had captured. Djarin then refused to accept payment in Imperial credits, forcing Karga to pay him in Calamari Flan, after which he told of an unusual job from individual known as the Client associated with an Imperial remnant. Karga was pleased when Djarin completed the job and after congratulating him gave him a new bounty to hunt down. Djarin however soon had a change of heart and rescued the Child. ",
        home:"Alderaan",
        Species: "Human",
        gender: "Female",
        eye: "Brown",
        skin:"Dark",
        color: "eptitle eptitlecolor2",
    },
    {
        id: 6,
        name: "IG-11",
        image: "/assets/images/eps/s01e03vul.jpg",
        imagescn: "/assets/images/character/IG.png",
        imagescn2: "/assets/images/character/IG2.png",
        imagescn3: "/assets/images/character/IG3.png",
        sum: "a masculine IG-series droid who worked as a bounty hunter around 9 ABY. Part of a series of assassin droids largely outlawed in the galaxy, IG-11 was programmed to follow protocols of the Bounty Hunters' Guild, and had built-in last-ditch failsafes to prevent himself from being captured while working as a hired gun. The droid had a thin body built on an armored substrate that could withstand repeated assaults, and was both reliable and durable. Around 9 ABY, IG-11 was destroyed by Din Djarin while attempting to kill the Child, though he was later repaired and re-programmed by the Ugnaught Kuiil in order to assist the retired vapor farmer.  ",
        home:"Alderaan",
        Species: "Assassin Droid",
        gender: "Masculine Programming",
        eye: "Red",
        skin:"Gray and Bronze",
        color: "eptitle eptitlecolor2",
    },
    {
        id: 7,
        name: "The Client",
        image: "/assets/images/eps/s01e03vul.jpg",
        imagescn: "/assets/images/character/Client.png",
        imagescn2: "/assets/images/character/Client2.png",
        imagescn3: "/assets/images/character/Client3.png",
        sum: "a masculine IG-series droid who worked as a bounty hunter around 9 ABY. Part of a series of assassin droids largely outlawed in the galaxy, IG-11 was programmed to follow protocols of the Bounty Hunters' Guild, and had built-in last-ditch failsafes to prevent himself from being captured while working as a hired gun. The droid had a thin body built on an armored substrate that could withstand repeated assaults, and was both reliable and durable. Around 9 ABY, IG-11 was destroyed by Din Djarin while attempting to kill the Child, though he was later repaired and re-programmed by the Ugnaught Kuiil in order to assist the retired vapor farmer.  ",
        home:"Unknown",
        Species: "Human",
        gender: "Male",
        eye: "Brown",
        skin:"GLight",
        color: "eptitle eptitlecolor2",
    },
    
    {
        id: 8,
        name: "The Dark Saber",
        image: "/assets/images/eps/s01e03vul.jpg",
        imagescn: "/assets/images/character/Saber.png",
        imagescn2: "/assets/images/character/Saber2.png",
        imagescn3: "/assets/images/character/Saber3.png",
        sum: "The Darksaber was an ancient and unique black-bladed lightsaber created by Tarre Vizsla, the first Mandalorian ever inducted into the Jedi Order, prior to 1019 BBY. The weapon was kept in the Jedi Temple after Vizsla's passing, but members of House Vizsla stole the saber in a conflict with the Jedi during the fall of the Old Republic. The Darksaber was passed down, generation to generation, by the ancestors of Pre Vizsla, who held onto the weapon even after the pacifist ideals of the New Mandalorians replaced the warrior ways of Mandalore. By 21 BBY, the Darksaber was in the possession of Pre Vizsla, the leader of Death Watch during the Clone Wars.  ",
        home:"Unknown",
        Species: "Kyber Crystal",
        gender: "N/A",
        eye: "N/A",
        skin:"Black",
        color: "eptitle eptitlecolor2",
        colorcard: "epcardcolor3 stretched-link"
    },
    
];